# Site settings
title: Blog
description: "My personal blog for aurele.oules.com"
url: "http://aurele.oules.com/blog"
author:
  name: "Aurèle Oulès"
  email: "aurele@oules.com"
  url: "http://aurele.oules.com"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
    - jekyll-paginate  

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

